openapi: 3.0.0
paths:
  /device/status:
    put:
      operationId: DeviceController_setStatus
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceStatusDto"
      responses:
        "200":
          description: Device status has been successfully enabled.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Device
  /device/token:
    put:
      operationId: DeviceController_setDeviceToken
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceTokenDto"
      responses:
        "200":
          description: Device status has been successfully enabled.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Device
  "/device/generate/{deviceId}":
    get:
      operationId: DeviceController_generateToken
      parameters:
        - name: deviceId
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: Generate and set new 6 digit token.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Device
  /order/status:
    put:
      operationId: OrderController_setStatus
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderStatusDto"
      responses:
        "200":
          description: Updates order status.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Order
info:
  title: ThyStreet
  description: Thy Street APIs are completely RESTful and all our responses are
    returned in JSON.
  version: 0.0.1
  contact:
    name: Support
    url: https://github.com/thystreet/thystreet/discussions
    email: support@thystreet.com
  termsOfService: https://thystreet.com/policies/tos
  x-logo:
    url: https://thystreet.com/svg/logo.svg
    altText: Thy Street logo
tags: []
servers:
  - url: https://cheffy-api.thystreet.com/api/v1
    description: Thystreet public API for controlling your device details
    variables: {}
components:
  securitySchemes:
    thystreetAuth:
      type: http
      scheme: basic
      description: Base64 format of api_key:api_secret
  schemas:
    DeviceStatusDto:
      type: object
      properties:
        deviceId:
          type: string
          description: Device ID
          nullable: false
        available:
          type: boolean
          description: Set current device availablity
          nullable: false
      required:
        - deviceId
        - available
    DeviceTokenDto:
      type: object
      properties:
        deviceId:
          type: string
          description: Device ID
          nullable: false
        token:
          type: boolean
          description: "Set device token "
          nullable: false
          maxLength: 6
          minLength: 6
      required:
        - deviceId
        - token
    OrderStatusDto:
      type: object
      properties:
        orderId:
          type: string
          description: Order ID
          nullable: false
        status:
          type: string
          description: Set order status
          enum:
            - CONFIRMED
            - COMPLETED
          nullable: false
      required:
        - orderId
        - status
security:
  - thystreetAuth: []
