openapi: 3.0.0
paths:
  /device/details:
    put:
      operationId: setDetails
      summary: Toggle your device tariff when your device goes online using this api.
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SetDeviceDetailsDto"
      responses:
        "200":
          description: Device status has been successfully enabled.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Device
  /device/token:
    put:
      operationId: setToken
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DeviceTokenDto"
      responses:
        "200":
          description: Device status has been successfully enabled.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Device
  "/device/generate/{deviceId}":
    get:
      operationId: generateToken
      parameters:
        - name: deviceId
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: Generate and set new 6 digit token.
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Device
  "/order/params/{orderToken}":
    get:
      operationId: getOrderById
      parameters:
        - name: orderToken
          required: true
          in: path
          description: This is the id recieved from the qrcode or on your webhook
          allowEmptyValue: false
          example: thystreet-FucAdwCipV6nLlVsesnu
          schema:
            type: string
      responses:
        "200":
          description: Returns order information for the given id
        "400":
          description: Invalid order token
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Order
  "/order/status/{orderToken}":
    put:
      operationId: setStatus
      parameters:
        - name: orderToken
          required: true
          in: path
          description: This is the id recieved from the qrcode or on your webhook
          allowEmptyValue: false
          example: thystreet-FucAdwCipV6nLlVsesnu
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/OrderStatusDto"
      responses:
        "200":
          description: Updates order status.
        "400":
          description: Invalid order token
        "401":
          description: Unauthorized.
        "403":
          description: Forbidden.
      tags:
        - Order
info:
  title: Thy Street
  description: These are API's to easily manage your Thy Street device public
    pages. Thy Street APIs are completely RESTful and all our responses are
    returned in JSON.
  version: 0.0.2
  contact:
    name: Support
    url: https://github.com/thystreet/thystreet/discussions
    email: support@thystreet.com
  termsOfService: https://thystreet.com/policies/tos
  x-logo:
    url: https://thystreet.com/svg/logo.svg
    altText: Thy Street logo
tags: []
servers:
  - url: https://cheffy-api.thystreet.com/api/v1
    description: Thystreet public API for controlling your device details
    variables: {}
components:
  securitySchemes:
    thystreetAuth:
      type: http
      scheme: basic
      description: Base64 format of api_key:api_secret
  schemas:
    SetDeviceDetailsDto:
      type: object
      properties:
        deviceId:
          type: string
          description: Device ID
          nullable: false
        tariff:
          type: boolean
          description: Toggle device tariff on public page
          nullable: false
      required:
        - deviceId
        - tariff
    DeviceTokenDto:
      type: object
      properties:
        deviceId:
          type: string
          description: Device ID
          nullable: false
        token:
          type: boolean
          description: "Set device token "
          nullable: false
          maxLength: 6
          minLength: 6
      required:
        - deviceId
        - token
    OrderStatusDto:
      type: object
      properties:
        status:
          type: string
          description: Set order status
          enum:
            - CONFIRMED
            - PENDING
            - COMPLETED
            - FAILED
          nullable: false
      required:
        - status
security:
  - thystreetAuth: []
