config_version: '1.4'
container_opts:
  image: datadog/apigentools:latest
  environment:
    OPENAPI_GENERATOR_VERSION: 5.2.0
languages:
  javascript:
    generation:
      default:
        commands:
          - commandline:
            - function: openapi_generator_generate # expands to the default generation command
            - --remove-operation-id-prefix
            - --verbose
            description: Generate code using openapi-generator
    # downstream_templates:
    #   downstream-templates/java/README.md: README.md
    github_org_name: thystreet
    github_repo_name: thystreet-javascript-sdk
    library_version: "0.0.1"
    version_path_template: "{{spec_version}}"
  typescript:
    generation:
      default:
        commands:
          - commandline:
            - function: openapi_generator_generate # expands to the default generation command
            - --remove-operation-id-prefix
            - --verbose
            description: Generate code using openapi-generator
    # downstream_templates:
    #   downstream-templates/java/README.md: README.md
    github_org_name: thystreet
    github_repo_name: thystreet-typescript-sdk
    library_version: "0.0.1"
    version_path_template: "{{spec_version}}"
  python:
    generation:
      default:
        commands:
          - commandline:
            - function: openapi_generator_generate # expands to the default generation command
            - --remove-operation-id-prefix
            - --verbose
            description: Generate code using openapi-generator
    github_org_name: thystreet
    github_repo_name: thystreet-python-sdk
    library_version: "0.0.1"
    version_path_template: "{{spec_version}}"
  cpp-tiny:
    generation:
      default:
        # templates:
        #   patches:
        #     - template-patches/cpp-tiny-basepath.patch
        #   source:
        #     type: openapi-jar
        #     jar_path: /usr/bin/openapi-generator-cli.jar
        #     templates_dir: cpp-tiny
        commands:
          - commandline:
            - function: openapi_generator_generate # expands to the default generation command
            - --remove-operation-id-prefix
            - --verbose
            description: Generate code using openapi-generator
    downstream_templates:
      downstream-templates/cpp-tiny/library.json: "v1/library.json"
      #downstream-templates/cpp-tiny/root.cert: "v1/root.cert"
    github_org_name: thystreet
    github_repo_name: thystreet-pio-sdk
    library_version: "0.0.1"
    version_path_template: "{{spec_version}}"
  openapi:
    generation:
      default:
        commands:
          - commandline:
            - function: openapi_generator_generate # expands to the default generation command
            - --remove-operation-id-prefix
            - --verbose
            description: Generate code using openapi-generator
    downstream_templates:
      downstream-templates/cpp-tiny/library.json: "v1/library.json"
      downstream-templates/cpp-tiny/root.cert: "v1/root.cert"
    github_org_name: thystreet
    github_repo_name: docs.github.com
    library_version: "0.0.1"
    version_path_template: "{{spec_version}}"
spec_sections:
  v1:
    - thystreet.yaml
spec_versions: ["v1"]
user_agent_client_name: "ThyStreet"
