name: Generate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install apigentools
        run: pip install apigentools

      - name: Validate spec file
        run: apigentools validate

      - name: Generate clients
        env:
          APIGENTOOLS_GIT_VIA_HTTPS: true
          APIGENTOOLS_GIT_VIA_HTTPS_INSTALLATION_ACCESS_TOKEN: ${{ github.token }}
        run: apigentools generate --clone-repo

      - name: Align permissions of generated code
        run: |
          sudo chown -R ${USER}:${USER} generated
      - name: Push client repos
        if: github.event_name == 'push'
        env:
          APIGENTOOLS_GIT_VIA_HTTPS: true
          APIGENTOOLS_GIT_VIA_HTTPS_INSTALLATION_ACCESS_TOKEN: ${{ github.token }}
        run: |
          git config --global user.email "akash@thystreet.com"
          git config --global user.name "Akash"
          apigentools push --skip-if-no-changes
